version: '3.9'

services:
  web:
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    container_name: django_crm
    ports:
      - 8000:8000
    volumes:
      - ./:/django_crm
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: admin123
    ports:
      - 5432:5432
